service: MessageProcessorLambdaService

custom:
  region: <region>
  accountId: <accountId>
  functionName: MessageProcessorLambdaFunction
  writeEnvVars:
    REGION: ${self:custom.region}
    SACCOUNT_ID: ${self:custom.accountId}
    FUNCTION_NAME: ${self:custom.functionName}

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:${self:custom.region}:${self:custom.accountId}:log-group:/aws/lambda/${self:service}-${self:custom.functionName}


functions:
  MessageProcessorLambdaFunction:
    handler: handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:${self:custom.region}:${self:custom.accountId}:message-processor

#aws creates default log group for lambda and a few other services
# resources:
#   Resources:
#     MessageProcessorLambdaFunctionLogGroup:
#       Type: AWS::Logs::LogGroup
#       Properties:
#         LogGroupName: /aws/lambda/${self:service}-${self:custom.functionName}
#         RetentionInDays: 30

plugins:
  - serverless-plugin-write-env-vars

